### ISSUE TITLE
Add Awesome code.gouv.fr ?

### ISSUE THREAD

**Issue by bzg** [ecosyste-ms/awesome#264]
Would it make sense to add the list of Awesome code.gouv.fr software, published/maintained by French public sector organizations?

See e.g. https://code.gouv.fr/fr/awesome/ and https://code.gouv.fr/data/awesome-codegouvfr.json

**Comment by andrew** [comment]
The code in this repo only really works for aweosme lists that are repos, I'd have to write something custom to support that, alternatively you could export the json into a markdown file in a repo on a regular basis?

**Comment by andrew** [comment]
I have an example: https://github.com/andrew/ultimate-awesome/ which has a github action: https://github.com/andrew/ultimate-awesome/blob/main/.github/workflows/update.yml which fetches some rendered markdwon from a server and commits the result once per day. 

It does mean creating a markdown endpoint on your webserver though.

**Comment by bzg** [comment]
Thanks for the pointers, I will create the endpoint on the server and update the repo with the workflow you shared.

**Comment by bzg** [comment]
It's now done here: https://github.com/codegouvfr/awesome-codegouvfr

The README.md in the repo is updated every day by fetching upstream info from http://code.gouv.fr/data/awesome-codegouvfr.md
